### ISSUE TITLE
Be more verbose

### ISSUE THREAD

**Issue by willirath** [ESM-VFC/esm-vfc-catalogs#12]
Maybe add a status bar to the download script in https://github.com/ESM-VFC/esm-vfc-catalogs/blob/7ba5f70d6fa864ce234cb61960823b8d5d1c37a3/esmvfc_cattools/fetching.py#L29.

**Comment by suvarchal** [comment]
[tqdm](https://tqdm.github.io/) could be easy to add.

**Comment by willirath** [comment]
Sounds good! I was playing with it this morning and ran into https://github.com/tqdm/tqdm/issues/864 which is a problem when the file size is not known up front. But we do know the file size for Zenodo downloads. @suvarchal Do you want to do this?

**Comment by suvarchal** [comment]
I think we do know the size, at least from the head request. I will try it out and could happily take up the task, but on low priority for next 2 weeks, if that is ok.

**Comment by willirath** [comment]
No problem, take your time.

**Comment by willirath** [comment]
Done. Closing.
