### ISSUE TITLE
careful with libcurl

### ISSUE THREAD

**Issue by suvarchal** [ESM-VFC/esm-vfc-catalogs#14]
Watch out when installing requirements from pip like `pip install -r requirements.txt`,  pycurl might be compiled against a different version of libcurl then present on current system this might lead to import error like:
  ```pycurl: libcurl link-time version (7.68.0) is older than compile-time version (7.69.1)``` 

In anycase using conda for pycurl is recommended.

**Comment by willirath** [comment]
Closing here as I'm moving the zenodo download to a separate repo.
