### ISSUE TITLE
Add FESOM2 data

### ISSUE THREAD

**Issue by willirath** [ESM-VFC/esm-vfc-catalogs#8]
First example dataset is here: https://zenodo.org/record/3819896

From the [the pyfesom2 docs](https://pyfesom2.readthedocs.io/), I gather that the mesh will be loaded from a Path. So we could use a Zip file and open it via [`zipfile`](https://docs.python.org/3/library/zipfile.html#module-zipfile). Not sure this is possible with tar archives as well?

**Comment by willirath** [comment]
@koldunovn We really should switch to zip archives for the mesh info as there's much more robust handling of zip as a file system in intake / fsspec than there is for tar (see https://github.com/intake/intake/issues/499).

**Comment by koldunovn** [comment]
Ok, got it. I think I will just upload mushes separately. There also is no problem to have mesh files separatelly for small meshes at least.

**Comment by willirath** [comment]
This is solved in #9. Thanks @suvarchal for figuring out the way to deal with FESOM data in #8!
